name: CI/CD for React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        cd your-react-app-directory
        npm install

    - name: Run Unit Tests
      run: |
        cd your-react-app-directory
        npm test

    - name: Build React App
      run: |
        cd your-react-app-directory
        npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: main # Change this if your GitHub Pages branch is different
