name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

      - name: Build and Deploy to GitHub Pages
        if: success()
        run: |
          npm run build
          echo "https://chamodmalintha.github.io/React-Custom-Hook/" > build/CNAME
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add build
          git commit -m "Build and deploy to GitHub Pages"
          git subtree push --prefix build origin gh-pages
